project:
  type: website

website:
  title: "Henry Johnson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Projects.qmd

  page-footer:
    right: "&copy; 2024, Henry Johnson"





format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
    
execute:
  freeze: auto

editor: visual

